openapi: 3.0.0
info:
  title: Seinfeld Character API
  description: API to retrieve, create, update, and delete Seinfeld characters
  version: 1.0.0
  contact:
    name: Seinfeld Fan Club

servers:
  - url: http://localhost:3000
    description: Local server

tags: 
  - name: Characters
    description: Operations related to Seinfeld characters

paths:
  /characters:
    get:
      summary: Get all characters
      description: Retrieve a list of all Seinfeld characters
      operationId: getCharacters
      tags:
        - Characters
      responses:
        '200':
          description: A list of Seinfeld characters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
  /characters/{id}:
    get:
      summary: Get a character by ID
      description: Retrieve details of a Seinfeld character by ID
      operationId: getCharacterById
      tags:
        - Characters
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The character ID
      responses:
        '200':
          description: Details of a Seinfeld character
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        '404':
          description: Character not found
    put:
      summary: Update a character by ID
      description: Update an existing Seinfeld character by ID
      operationId: updateCharacterById
      tags:
        - Characters
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The character ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Character'
      responses:
        '200':
          description: Character updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        '404':
          description: Character not found
    delete:
      summary: Delete a character by ID
      description: Delete an existing Seinfeld character by ID
      operationId: deleteCharacterById
      tags:
        - Characters
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The character ID
      responses:
        '204':
          description: Character deleted successfully
        '404':
          description: Character not found
components:
  schemas:
    Character:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the character
          example: jerry_seinfeld
        first_name:
          type: string
          description: First name of the character
          example: Jerry
        last_name:
          type: string
          description: Last name of the character
          example: Seinfeld
        age:
          type: integer
          description: Age of the character
          example: 35
        first_episode:
          type: string
          description: Title of the first episode the character appeared in
          example: The Seinfeld Chronicles
      required:
        - id
        - first_name
        - last_name
        - age
        - first_episode
  